@host = http://localhost:5000/api/
@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmZmYxMjcwNGEzNjk2NzE1Y2ZiZTEyYyIsIm5hbWUiOiJJc3VydSBHb2Rha2FuZGEiLCJlbWFpbCI6ImlzdXJ1LmcuYWV0dXJudW1AZ21haWwuY29tIiwicm9sZSI6Im1hbmFnZXIiLCJhdmF0YXIiOiIvL3d3dy5ncmF2YXRhci5jb20vYXZhdGFyL2YzYTc0YzU5YjYwNmI2ZjllYTY4YzE1NWEwMmNmOGVjP3M9MjAwJnI9cGcmZD1tbSIsImlhdCI6MTYxMTIzNTgyMywiZXhwIjoxNjExNTk1ODIzfQ.YaROHHQJcxc2ZzeyuFrkOhwJUwWIzUDpoavPFOY36kw

# Sign in
POST {{host}}auth HTTP/1.1
Content-Type: application/json

{
    "email": "isuru.g.aeturnum@gmail.com",
    "password": "Asdf123"
}

###

# Retrieve dashboard details
POST {{host}}users HTTP/1.1
Content-Type: application/json
x-auth-token: {{authToken}}

{
    "name": "Donal Trump",
    "email": "isurugo93+10@gmail.com",
    "role": "worker",
    "password": "Asdf123"
}

###

# Get all users
GET  {{host}}users?offset=1&limit=5&search_term= HTTP/1.1
x-auth-token: {{authToken}}

###

# Get user by id
GET  {{host}}users/5fff12704a3696715cfbe12c HTTP/1.1
x-auth-token: {{authToken}}

###

# Update user by id
PUT  {{host}}users/6009462eaacde915fe7bd264 HTTP/1.1
Content-Type: application/json
x-auth-token: {{authToken}}

{
    "name": "Bradrr",
    "email": "isuru.g@aeturnum.com",
    "role": "worker"
}

###

# Delete user by id
DELETE  {{host}}users/6009a53f9827da570e6b44cb HTTP/1.1
x-auth-token: {{authToken}}
